#!/usr/bin/env bash
# fixing docker issues

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /tee/init.d/apache2 restart
